### ISSUE TITLE
Vehicle class missing

### ISSUE THREAD

**Issue by artung** [egueli/TraCI4J#13]
Hi,
I'm trying to run the example GetVehicleInfo but it cannot "import it.polito.appeal.traci.Vehicle".
This class is missing in package it.polito.appeal.traci. Has it a new name or something similar?
Thanks

**Comment by egueli** [comment]
Hi,
that class (and others) is auto-generated. Starting from commit 1583a249c7e827310dbbaa4b3334c497408457f2 (currently in master), if you open the library in Eclipse as a project, it should generate that class automatically. If that doesn't happen, please provide me any information that may be useful: errors, console logs...

You can also get the auto-generation by running Ant on the library's main directory.

**Comment by egueli** [comment]
Closing because there were no further updates on this issue.
