### ISSUE TITLE
Build error: TraCI4J is missing required source folder: src/java-gen

### ISSUE THREAD

**Issue by stteffen58** [egueli/TraCI4J#14]
Hi,
I have just cloned the repository from github and receive the following build error: TraCI4J is missing required source folder: src/java-gen

Any advice how I can fix this error?
Thanks!!

**Comment by egueli** [comment]
Hi,
I could reproduce this issue.
Just fixed in master, please tell me it it works for you too.

**Comment by stteffen58** [comment]
Works properly now. Thanks a lot!

**Comment by stteffen58** [comment]
Works properly now. Thanks a lot!

**Comment by lizalemos** [comment]
Hi, 
I have the same error here. TraCI4J is missing 'target/src/java-gen'
Any tip how to fix this?

Thanks

**Comment by CageZ** [comment]
You have to build it this way:
`mvn compile`
