### ISSUE TITLE
TrafficLight.xml wrong constants

### ISSUE THREAD

**Issue by felix-loesch** [egueli/TraCI4J#16]
I found the following errors in TrafficLight.xml:
1. ChangePhaseIndex: The constant must be it.polito.appeal.traci.protocol.Constants.TL_PHASE_INDEX instead of it.polito.appeal.traci.protocol.Constants.TL_CURRENT_PHASE
2. ReadAssumedNextSwitchTime: The constant must be
it.polito.appeal.traci.protocol.Constants.TL_NEXT_SWITCH instead of
it.polito.appeal.traci.protocol.Constants.TL_RED_YELLOW_GREEN_STATE

**Comment by egueli** [comment]
Fixed. Thanks!
