### ISSUE TITLE
ESP8266 WiFi download to flash

### ISSUE THREAD

**Issue by WantDoIt** [egueli/TraCI4J#18]
hi~
     I want to download binary file to ESP chip. I read esptool.py code at https://github.com/themadinventor/esptool/blob/master/esptool.py  .  There are some operations in epstool.py code ,such as "if args.operation == 'read_mac':" "if args.operation == 'write_flash':".
     Now ，I want to download file to flash. However, I don't know  which operation should be performed？
If there are many operations should be performed,what should I do about operating sequence?
     Could you give me some help to solve it ？
     Thank you!!!

**Comment by egueli** [comment]
Hi,
have a look at https://github.com/themadinventor/esptool/blob/master/README.md, especially the Examples section. Usually a firmware for the ESP is first split into two blocks (called 00000 and 40000), then downloaded to the chip. The first example will do the splitting, the second will download them.
I hope that helps. Cheers!
