### ISSUE TITLE
Is there any api for this?

### ISSUE THREAD

**Issue by echozheng** [egueli/TraCI4J#19]
I just wanna ask if there is any api for this?
finding how the functions work takes me a long time.
many thanks.

**Comment by egueli** [comment]
Unfortunately, there's no documentation as such.

But the methods of this test class can also be seen as examples:
https://github.com/egueli/TraCI4J/blob/master/test/java/it/polito/appeal/traci/test/TraCITest.java

For the basic structure of a program that uses TraCI4J, you can look at one of the examples:
https://github.com/egueli/TraCI4J/tree/master/examples/it/polito/appeal/traci/examples

By mixing the two you can figure out how to interface your program to SUMO via TraCI4J.

I hope this helps.

**Comment by echozheng** [comment]
many thanks.
