### ISSUE TITLE
"sumo.exe" file name for win64

### ISSUE THREAD

**Issue by podorozhnick** [egueli/TraCI4J#20]
From sumo version 0.24 they didn't use file name "sumo64.exe" for Win64 - just "sumo.exe".

**Comment by egueli** [comment]
Thanks @CageZ for the patch, just applied. @podorozhnick could you check if it works for you?

**Comment by podorozhnick** [comment]
ok, maybe I'll check it later. For my build I just commented this "+= "64" (or just rename sumo.exe to sumo64.exe) and all is working fine. 
p.s.: @egueli Can I contact you anywhere? - I have some questions about getting Lane by Lat-Long coordinates.

**Comment by egueli** [comment]
@podorozhnick you can write to the mailing list https://lists.sourceforge.net/lists/listinfo/traci4j-user

**Comment by podorozhnick** [comment]
@egueli  thanks, done)
