### ISSUE TITLE
Definition of types Vehicle, Route, Lane...

### ISSUE THREAD

**Issue by biurrun4** [egueli/TraCI4J#24]
Hello,

I was checking out this library and after looking allover the different classes, I can't tell where the different SUMO objects are defined exactly. I mean, let's say we can have a repository of vehicles, Repository<Vehicle> repo1. My question is, where is this "Vehicle" type defined?

So, what I am saying is, the library works perfectly, but I am just trying to understand its performance.
Thanks in advance

**Comment by egueli** [comment]
Hi,
The source code hosted on Git doesn't contain the SUMO object classes, because they are generated dynamically at build time.
The code generation is based upon the XML files in src/xml/traciObjects.
