### ISSUE TITLE
connect SUMO to Unity3D

### ISSUE THREAD

**Issue by ghost** [egueli/TraCI4J#34]
Hello, how can I connect SUMO to Unity3D? I have cloned your projects and simulation is running but unfortunately connection between Unity3D with SUMO is not working.

**Comment by egueli** [comment]
Hi, TraCI is outdated and not supported anymore. Please use Libtraci (https://sumo.dlr.de/docs/Libtraci.html) that is maintained by the SUMO developers themselves.
